"""Record when ASAP actually PUBLISHES a dekad, because we ratified a
staleness rule we could not measure.

The rule is "no new dekad for more than 20 days", which is a clock on
PUBLICATION. The payload recorded only `dekad`, which is the label of
the observation window and, worse, its START. So three people measured
three different ages of the same file on 2026-08-06:

  from the dekad label, 11 July      26 days
  from the window close, 20 July     17 days
  from publication                   unmeasurable, nothing recorded it

Only the third is the rule. This records it.

The endpoint is cheap and unambiguous: it returns a small JSON object
when a dekad is published and a literal `[]` when it is not, so one GET
per dekad decides whether a 30 MB download is worth starting. It lives
at the SITE ROOT, not under /api/ or /export/, which cost a wrong
answer once.

    python crops/probe_asap.py            # probe recent dekads, log
    python crops/probe_asap.py --json     # machine-readable, no write

Writes crops/data/publication_log.json, which is committed: it is an
audit trail of what the source did and when we saw it, in the same
spirit as the snapshots. It can only ever be appended to, because
first_seen is by definition the first time we saw it.
"""
import argparse
import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LOG = HERE / "data" / "publication_log.json"

# A first sighting this long after a dekad's window closed cannot be a
# publication event, so its first_seen is when we started looking. 20
# days is the staleness bound already agreed for this source: a genuine
# publication is always inside it, and anything outside it would have
# fired that rule first.
BACKFILL_AFTER_DAYS = 20
BASE = ("https://agricultural-production-hotspots.ec.europa.eu"
        "/getIndicatorsInfo.php")
INDICATOR = "zFPARc"


def dekads_around(today: dt.date, back: int = 6, ahead: int = 1):
    """The dekad labels near today. ASAP dekads start on the 1st, 11th
    and 21st, so they are not evenly spaced and cannot be generated by
    adding ten days."""
    out = []
    y, m = today.year, today.month
    for _ in range(back + ahead + 1):
        for day in (1, 11, 21):
            out.append(dt.date(y, m, day))
        m -= 1
        if m == 0:
            y, m = y - 1, 12
    cutoff = today + dt.timedelta(days=10 * ahead)
    return sorted({d for d in out if d <= cutoff})


def is_published(dekad: dt.date, timeout: int = 30):
    """True / False / None where None means the probe itself failed.
    None is NOT False: treating a network error as 'not published' is
    how a stall gets recorded as the source being slow."""
    url = f"{BASE}?dekad={dekad:%Y%m%d}&indicator_name={INDICATOR}"
    p = subprocess.run(["curl", "-sS", "--max-time", str(timeout), url],
                       capture_output=True, text=True)
    if p.returncode != 0:
        return None
    body = (p.stdout or "").strip()
    if body.startswith("[]"):
        return False
    if body.startswith("{"):
        try:
            return bool(json.loads(body))
        except ValueError:
            return None
    return None


def load():
    if LOG.exists():
        return json.loads(LOG.read_text(encoding="utf-8"))
    return {"_what": "when each ASAP dekad was FIRST SEEN published by "
                     "us. first_seen is an upper bound on the true "
                     "publication time, never the exact moment, because "
                     "it depends on when we last probed.",
            "_rule": "the staleness bound is 20 days between "
                     "publications, not 20 days since a dekad label",
            "indicator": INDICATOR, "dekads": {}}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true",
                    help="print the result and write nothing")
    ap.add_argument("--back", type=int, default=6)
    args = ap.parse_args()

    today = dt.date.today()
    first_ever = not LOG.exists()
    log = load()
    seen = log["dekads"]
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()

    # On the first run every dekad is found on the same day, so
    # first_seen would say "0 days old" about a dekad published weeks
    # ago. That is a measurement of when we started looking, not of the
    # source, and it is exactly the shape of defect this log exists to
    # stop. Backfilled entries are marked and never used for an age.
    if first_ever:
        log["_backfill_note"] = (
            "Entries marked backfilled were already published when "
            "probing began on this date. Their first_seen is the first "
            "probe, not the publication, so no age may be computed from "
            "them. Ages are meaningful only for dekads first seen after "
            "this run.")

    newest, failures = None, 0
    for d in dekads_around(today, back=args.back):
        key = f"{d:%Y-%m-%d}"
        if seen.get(key, {}).get("published"):
            newest = max(newest or key, key)
            continue
        ok = is_published(d)
        if ok is None:
            failures += 1
            print(f"  {key}  PROBE FAILED (not recorded as unpublished)")
            continue
        if ok:
            # first_seen is only written once, ever.
            seen.setdefault(key, {})
            fresh = "first_seen" not in seen[key]
            seen[key].update({"published": True,
                              "first_seen": seen[key].get("first_seen", now)})
            # BACKFILL IS A PROPERTY OF THE DEKAD, NOT OF THE RUN.
            #
            # This used to be `fresh and first_ever`, so only the very
            # first probe of an empty log marked anything. Any later run
            # reaching further back then recorded months-old dekads as
            # genuinely first seen today: on 2026-08-16 a default-range
            # probe wrote 15 entries claiming we first saw January's
            # dekad that afternoon, unflagged, which would have
            # corrupted the one statistic this log exists to produce.
            #
            # A dekad cannot have been published today if its window
            # closed long ago. If we are seeing it for the first time
            # more than the staleness bound after it closed, either the
            # source stalled and we would have caught that, or we simply
            # were not looking. Either way first_seen is when we started
            # looking, not when it published, and no age may come from
            # it.
            stale_first_sight = (today - d).days - 10 > BACKFILL_AFTER_DAYS
            if fresh and (first_ever or stale_first_sight):
                seen[key]["backfilled"] = True
            newest = max(newest or key, key)
            print(f"  {key}  published"
                  + ("  (backfilled, age unknown)"
                     if seen[key].get("backfilled")
                     else "  (NEW)" if fresh else ""))
        else:
            print(f"  {key}  not yet")

    log["dekads"] = seen
    log["last_probed"] = now
    log["newest_published"] = newest

    if newest:
        fs = seen[newest].get("first_seen")
        backfilled = seen[newest].get("backfilled", False)
        age = None
        if fs and not backfilled:
            age = (dt.datetime.now(dt.timezone.utc)
                   - dt.datetime.fromisoformat(fs)).days
        log["days_since_newest_first_seen"] = age
        log["newest_is_backfilled"] = backfilled
        print(f"\nnewest published dekad: {newest}")
        if backfilled:
            print("  publication date UNKNOWN: it was already published "
                  "when probing began, so the bound cannot be evaluated "
                  "yet. It becomes measurable at the next new dekad.")
        else:
            print(f"  first seen {fs}, {age} day(s) ago")
            if age is not None and age > 20:
                print("  PAST THE 20-DAY BOUND: two full publication "
                      "cycles with nothing new.")

    if args.json:
        print(json.dumps(log, indent=1))
        return 0
    LOG.write_text(json.dumps(log, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {LOG.relative_to(HERE.parent)}")
    return 1 if failures and newest is None else 0


if __name__ == "__main__":
    sys.exit(main())
