"""Render the Fire channel home page, docs/fires/index.html.

Styling comes from tokens.py, never from hardcoded hexes. Bulletin
rules that shape this layout: radius 0, no shadows or gradients, and
nothing enclosed on four sides, so rows are separated by hairlines
rather than boxed into cards. Product names set in mono, uppercase,
tracked; the house sets in Spectral.

Content comes from data/events.json, which is generated by
build_events.py from whole days only, so every number on this page is
a settled one.
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# tokens.py and run_brief.py both live at the repo root. Insert the path
# BEFORE importing either, so `python fires/build_page.py` works from a
# plain checkout without a PYTHONPATH incantation.
sys.path.insert(0, REPO)

import tokens as T  # noqa: E402
from run_brief import (ANALYTICS_SNIPPET, SITE_MASTHEAD_CSS,  # noqa: E402
                       lead_sentence, site_masthead)
# run_brief.py lives at the repo root and holds the single copy of the
# analytics tag. Import it rather than pasting a duplicate, so there is
# one source of truth to disable or rotate.
EVENTS = os.path.join(REPO, "data", "events.json")
OUT = os.path.join(REPO, "docs", "fires", "index.html")

TAG_TEXT = {
    "enso": "ENSO-loaded window",
    "non_enso": "not ENSO-linked",
    # D-076: no entry for a null tag. An untagged country renders no
    # tag at all rather than a word that means "we have not looked".
}


def _tag(e):
    """The attribution chip, or nothing at all.

    D-076: an untagged country gets no chip. "attribution pending" was
    the code's default fallback, so it appeared on nearly every row and
    told the reader only that we had not looked, which is not their
    problem.
    """
    a = e.get("attribution")
    if not a or a not in TAG_TEXT:
        return ""
    return f'<span class="tag tag-{a}">{TAG_TEXT[a]}</span>'


def _row(e):
    """One country row. Context is not an anomaly and must not look like
    one, and a thin multiple must not look sturdy."""
    href = e["href"]
    if href.startswith("fires/"):
        href = href[len("fires/"):]
    ctx = e.get("volume_context") and not e.get("anomalous")
    # A qualifier on its own line rather than run on to the claim. Taken
    # from the interim fix on main, whose reasoning is right and worth
    # keeping: "this is normal" is a result, not a caveat, so it is set
    # plain and never in a warning colour.
    note = ""
    if ctx:
        note = ('<span class="rowqual">within its historical range; '
                'shown for scale</span>')
    elif not e.get("anomalous") and e.get("pinned"):
        # "not unusual today" USED TO BE APPENDED HERE AND CONTRADICTED THE
        # ROW IT SAT ON. Spain, France and the UK all carry a title reading
        # "Second-heaviest fire week since 2012" or similar, and the note
        # denied it on the same line. Spain was the clearest: rank 2 of 14
        # with z=1.92, which is not "not unusual" by any reading we take.
        #
        # The mistake was treating "cleared no gate" as "nothing to see".
        # They are different claims and only the first is ours to make from
        # this payload. A country can miss every threshold and still be
        # having its second-heaviest week on record, which is exactly what
        # these rows are. So the note now says only why the row is present,
        # and the title is left to make the claim.
        note = ('<span class="rowqual">shown every week so this country '
                'can be checked, whatever it is doing</span>')
    elif e.get("multiple_unstable"):
        note = ('<span class="rowqual">small baseline; rank is the '
                'sturdier reading</span>')
    return f"""
      <a class="row{' ctx' if ctx else ''}" href="{href}">
        <span class="stat">{e['stat']}</span>
        <span class="rowmain">
          <span class="region">{e['region']}</span>
          <span class="claim">{e['title']}</span>{note}
        </span>
        {_tag(e)}
      </a>"""


# The prose above the weak list describes fire's gate in words, and words
# are as capable of drifting out of date as a comparison is. The headings
# name no number for that reason, but one sentence still commits: "whether
# it is setting a record" is only a fair description of the record signal
# while it means rank 1.
#
# So the description is pinned to the constants it paraphrases and the
# build fails if they move. This is the cheap half of the lesson the
# verdict field taught: a threshold copied into a second place needs
# something that notices when the copies disagree, and a guard cannot be
# forgotten where a ticket can.
_PROSE_ASSUMES = {"RECORD_RANK": 1}


def _check_prose_assumptions():
    from fires import build_events as _be
    for name, expected in _PROSE_ASSUMES.items():
        actual = getattr(_be, name)
        if actual != expected:
            raise SystemExit(
                f"fires/build_page.py: {name} is now {actual}, and the "
                f"prose under the weak-signal list was written for "
                f"{expected}. It tells the reader the second reading is "
                f"'whether it is setting a record', which stops being true "
                f"once more than the top week qualifies. Reword the note, "
                f"then update _PROSE_ASSUMES.")


def build(events_doc, font_prefix="../fonts/"):
    ev = events_doc["events"]
    window = ev[0]["source"] if ev else ""
    # The headline counted every country on the page and asserted all of
    # them were burning well above normal. Four are not: they are large,
    # above normal and explicitly NOT anomalous, and DR Congo sits at
    # exactly 1.0x. The live page said "15 countries are burning well
    # above their own seasonal normal" while its own data denied four of
    # them, which is a wrong claim rather than a loose one. It counts the
    # anomaly flag now, and the context countries are listed under their
    # own heading rather than folded into the number.
    anom = [e for e in ev if e.get("anomalous")]
    ctx = [e for e in ev if e.get("volume_context") and not e.get("anomalous")]
    rest = [e for e in ev if e not in anom and e not in ctx]

    # THE MULTIPLE-ALONE SPLIT. Fire emits `strength.verdict` for this and
    # the branch is on the VERDICT, never on `qualifies_on`. Their reason,
    # and it is right: comparing the signal list against ["multiple"] would
    # put fire's gate rule inside design's code, where it agrees today and
    # drifts silently the first time the gate moves, because the comparison
    # keeps evaluating and keeps returning something.
    #
    # What it fixes, on this week's data: Botswana at 2.5x sorted above the
    # United States at 2.3x and India at 2.2x, so a reader scanning down
    # read Botswana as the fourth most extreme fire situation on earth.
    # Botswana is 3rd in its own 14-year record with z=1.79, inside its
    # ordinary variation. The other two are having their heaviest weeks on
    # record. Sorting by multiple put the least corroborated country above
    # two of the best corroborated ones.
    weak = [e for e in anom
            if (e.get("strength") or {}).get("verdict") == "multiple_only"]
    strong = [e for e in anom if e not in weak]
    rows = [_row(e) for e in strong]
    weak_rows = [_row(e) for e in weak]
    ctx_rows = [_row(e) for e in ctx]
    rest_rows = [_row(e) for e in rest]

    # THE COUNT IS NOT A FINDING, SO IT IS NOT THE HEADLINE.
    #
    # This said "N countries are burning well above their own seasonal
    # normal". Tested against an empirical null on 2026-08-04, at
    # product's request and after crops reached the same conclusion
    # independently: running this gate on every historical year of the
    # same window, leave-one-out, an ORDINARY week produces 7.6
    # qualifiers, median 8, range 3 to 10. The ten we published ties the
    # historical maximum rather than exceeding it, and sits at the 85th
    # percentile. One year in six.
    #
    # Worse, the gate manufactures much of its own count. RECORD_RANK is
    # satisfied by each country exactly once across the record BY
    # CONSTRUCTION, so 94 countries over 13 years yields about seven
    # qualifiers every year whatever happens; it contributed 5 to 8 in
    # every year including the quiet one. A count with a floor under it
    # cannot be evidence of anything.
    #
    # The individual extremes are the finding and survive any null:
    # Greece at 11.5x is 4.5x its own previous record week. So the
    # headline leads with the largest anomaly and states the count
    # nowhere. The gate keeps RECORD_RANK for SELECTION, which is sound;
    # what it stops doing is generating a number we present as a claim.
    # Editor's approved sentence, shared with the front page so the two
    # surfaces cannot drift. This headline was changed to the leading
    # extreme before product's ruling arrived, which was right, but it
    # led with the AVERAGE multiple. Beating a record is a stronger kind
    # of claim than exceeding an average, and the average multiple is
    # closer in shape to the count we just removed. Editor's argument.
    # Leads on the best-corroborated extreme rather than the largest
    # multiple. Identical output this week, since Greece is both, and it
    # stops the headline being handed to a multiple-only country on a week
    # where one happens to top the sort. That follows editor's own argument
    # for the current sentence: a record is a stronger kind of claim than a
    # multiple over an average.
    lead = (strong or anom or ev or [None])[0]
    if lead:
        headline = lead_sentence(lead).rstrip(".") or (
            f"{lead['region']} is burning at {lead['stat']} its "
            f"average for this week of the year")
    else:
        headline = "No country is burning unusually this week"
    # The house masthead, shared with every other page rather than
    # reinvented here. Without it this page had no link home, no nav and
    # no About, so anyone landing on it first was stuck.
    # Listed, not counted. These are large and above their own normal
    # and did not clear the anomaly gate, so they belong on a world fire
    # map and are not news. The section says so in words rather than
    # relying on a reader noticing a lighter number.
    # The wording names NO THRESHOLD, deliberately. Saying "none is more
    # than two standard deviations above its own average" would encode
    # fire's gate in design's prose, which is the same drift the verdict
    # field exists to prevent, just moved from a comparison into a sentence.
    #
    # Nor does it say these countries are not unusual. Portugal, Syria and
    # Indonesia are each having their second-heaviest week since 2012 and
    # the row titles say so. The claim here is narrower and is the one the
    # payload supports: one reading is carrying this on its own.
    _check_prose_assumptions()
    weak_block = ("" if not weak_rows else
                  '<p class="sectionlabel">High against their own average, '
                  'and nothing else agrees</p>' +
                  "".join(weak_rows) +
                  '<p class="note">We take three readings of each country: '
                  'how it compares with its own average for this week of '
                  'the year, whether it is setting a record, and how far it '
                  'stands out from its own year-to-year spread. For the '
                  'countries above, at least two agree. For these, only the '
                  'first does. That does not make them quiet, and several '
                  'are having one of their heaviest weeks since 2012; it '
                  'means the evidence is thinner, so they are listed apart '
                  'rather than ranked among the others.</p>')
    # Pinned countries, previously rendered in the same list as the
    # anomalies with nothing but a row note to separate them. Given their
    # own heading now: Spain and France sit at second-heaviest since 2012
    # and appearing directly under the anomaly list read as a claim we had
    # not made.
    rest_block = ("" if not rest_rows else
                  '<p class="sectionlabel">Shown every week, whatever they '
                  'are doing</p>' + "".join(rest_rows) +
                  '<p class="note">These countries are on the page every '
                  'week so that a reader can check them rather than take '
                  'our word for which places matter. Their presence here is '
                  'not a signal in either direction; read the week each one '
                  'is having off its own row.</p>')
    ctx_block = ("" if not ctx_rows else
                 '<p class="sectionlabel">Large, and within their own '
                 'normal range</p>' + "".join(ctx_rows) +
                 '<p class="note">These countries are burning at or above '
                 'their own average for this week and did not clear the '
                 'anomaly gate. They are here because a fire map that '
                 'omitted them would misrepresent where the world is '
                 'burning, and they are listed separately because '
                 'presenting them as anomalies would misrepresent '
                 'whether it is unusual.</p>')
    # THE EXCLUSION IS STATED WHERE A READER SEES IT, not only in the log.
    #
    # Product's condition and it is not negotiable. Every data defect this
    # week was invisible because the artifact looked well formed, and a
    # seven-day window that quietly became five is that shape again.
    #
    # Design's lead_sentence already leads with the record comparison
    # rather than the multiple, which satisfies the other half of
    # product's ruling: a record is self-bounding, while a multiple on
    # five days is noisier than on seven and the page cannot show the
    # reader that difference.
    deg = events_doc.get("degraded")
    deg_note = ""
    if deg:
        MON = ["January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November",
               "December"]
        parts = []
        for d in deg["excluded"]:
            _, m, dd = d.split("-")
            parts.append(f"{int(dd)} {MON[int(m) - 1]}")
        days = (" and ".join(parts) if len(parts) < 3
                else ", ".join(parts[:-1]) + " and " + parts[-1])
        deg_note = (
            f'<p class="degnote">This week covers {deg["days_used"]} of '
            f'{deg["days_in_window"]} days. The NASA archive is incomplete '
            f'for {days}, so those days are excluded from this week\'s '
            f'counts and from every baseline they are measured against. '
            f'The comparison is like-for-like; it is shorter.</p>')
    house_masthead = site_masthead("../", active="fire")
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Fires | The Long Swell</title>
<style>
{T.font_faces_css(font_prefix)}
:root {{
{T.css_variables()}
}}
@media (prefers-color-scheme: dark) {{
  :root {{
{T.css_variables(dark=True)}
  }}
}}
:root[data-theme="dark"] {{
{T.css_variables(dark=True)}
}}
:root[data-theme="light"] {{
{T.css_variables()}
}}
* {{ box-sizing: border-box; }}
/* Line the shared masthead's shell up with this page's content column.
   Without these the masthead ran edge to edge against a 760px centred
   main. */
:root {{ --shell-max: 760px; --shell-pad: 24px; }}
body {{
  margin: 0; background: var(--paper); color: var(--ink);
  font-family: "{T.FONT_PROSE}", Georgia, serif;
  font-size: 17px; line-height: 1.55;
}}
main {{ max-width: 760px; margin: 0 auto; padding: 28px 24px 80px; }}

{SITE_MASTHEAD_CSS}
.masthead {{
  display: flex; align-items: baseline; gap: 14px;
  padding: 18px 0 10px; border-bottom: 2.4px solid var(--rule-45);
}}
.house {{ font-size: 19px; letter-spacing: -0.01em; }}
.product {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 12px; font-weight: 600; text-transform: uppercase;
  letter-spacing: {T.TRACK_PRODUCT}em; color: var(--fire);
}}
.masthead .when {{
  margin-left: auto;
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 11px; letter-spacing: {T.TRACK_LABEL}em;
  text-transform: uppercase; color: var(--ink-faint);
}}

h1 {{
  font-size: 34px; font-weight: 500; line-height: 1.16;
  letter-spacing: -0.015em; margin: 26px 0 12px; text-wrap: balance;
}}
.standfirst {{
  color: var(--ink-soft); margin: 0 0 6px; max-width: 60ch;
}}
.sectionlabel {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 11px; font-weight: 600; letter-spacing: {T.TRACK_LABEL}em;
  text-transform: uppercase; color: var(--ink-faint);
  margin: 38px 0 0; padding-bottom: 8px;
  border-bottom: 1px solid var(--ink);
}}

.row {{
  display: grid;
  grid-template-columns: 5.2rem 1fr auto;
  gap: 18px; align-items: baseline;
  padding: 15px 0; border-bottom: 1px solid var(--rule);
  text-decoration: none; color: inherit;
}}
/* A qualifier on a row that is not an anomaly. Plain, never a warning
   colour: styling a normal result as an alert is the amplification
   D-043 bars. */
.degnote {{
  color: var(--ink-soft); font-size: 14.5px; margin: 10px 0 0;
  padding-left: 12px; border-left: 2px solid var(--rule-45);
  max-width: 62ch;
}}
.rowqual {{
  display: block; color: var(--ink-soft); font-size: 13px;
  font-style: italic; margin-top: 2px;
}}
.row.ctx .stat {{ color: var(--ink-soft); }}
.row:hover .claim {{ text-decoration: underline; }}
.row:focus-visible {{ outline: 2px solid var(--fire); outline-offset: 3px; }}
.stat {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 30px; font-weight: 600; color: var(--fire);
  letter-spacing: -0.02em; font-variant-numeric: tabular-nums;
}}
.rowmain {{ display: flex; flex-direction: column; gap: 2px; }}
.region {{ font-size: 19px; font-weight: 500; }}
.claim {{ color: var(--ink-soft); font-size: 15.5px; }}
.tag {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 10.5px; letter-spacing: 0.04em; white-space: nowrap;
  padding: 3px 8px; align-self: center;
}}
.tag-non_enso {{ background: var(--tag-notlink-bg); color: var(--tag-notlink-fg); }}
.tag-enso {{ background: var(--tag-loaded-bg); color: var(--tag-loaded-fg); }}
.tag-pending {{ background: var(--tag-pending-bg); color: var(--tag-pending-fg); }}

.note {{
  margin: 22px 0 0; font-size: 14px; color: var(--ink-soft);
  max-width: 62ch;
}}
.foot {{
  margin-top: 44px; padding-top: 14px;
  border-top: 1px solid var(--ink);
  font-size: 13px; color: var(--ink-faint); max-width: 66ch;
}}
.foot p {{ margin: 0 0 9px; }}
.foot b {{ color: var(--ink-soft); font-weight: 500; }}
@media (max-width: 560px) {{
  .row {{ grid-template-columns: 4.2rem 1fr; }}
  .tag {{ grid-column: 2; justify-self: start; margin-top: 4px; }}
  h1 {{ font-size: 27px; }}
}}
</style>
{ANALYTICS_SNIPPET}
</head>
<body>
{house_masthead}
<main>
  <div class="masthead">
    <span class="product">Fires</span>
    <span class="when">{window}</span>
  </div>

  <h1>{headline}</h1>
  {deg_note}
  <p class="standfirst">Every figure below compares a country only with
  itself, against the same calendar week in each year since 2012. That
  is what separates an unusual week from a merely busy one.</p>

  <p class="sectionlabel">Against their own record</p>
  {''.join(rows)}
  {weak_block}
  {ctx_block}
  {rest_block}

  <p class="note">Ranked by how far above normal, not by size. Angola,
  DR Congo and Zambia each recorded more detections this week than
  anywhere on this list, and none of them appear on it: the southern
  African savanna burns on that scale every dry season, so all three
  sit at or near their own normal. Volume is not news; departure is.</p>

  <div class="foot">
    <p><b>What a detection is.</b> One satellite pixel, about 375 m
    across, seen radiating enough heat to be flagged as actively
    burning on a single overpass. A large fire front registers as many
    pixels at once, and a fire that keeps burning is counted again on
    every pass it stays hot. Detections are not burned area.</p>
    <p><b>Method.</b> NASA FIRMS, VIIRS on Suomi-NPP only so that every
    year is measured by the same sensor, low-confidence detections
    excluded, detections assigned to countries by national boundary
    polygons applied identically in all years. The window is seven
    whole UTC days, refreshed once daily, so no figure here is a
    partial day.</p>
    <p><b>Attribution.</b> Southern and western European fires are
    driven by heat, drought and wind, and people supply nearly all
    ignitions. Canadian boreal fire has its own drivers. None of this
    week's items is presented as an El Nino signal; each carries its
    own tag.</p>
  </div>
</main>
</body>
</html>
"""


def main():
    doc = json.load(open(EVENTS))
    html = build(doc)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(html)
    print(f"wrote {OUT} ({len(html):,} bytes, {len(doc['events'])} rows)")


if __name__ == "__main__":
    main()
