"""Render the Fire channel home page, docs/fires/index.html.

Styling comes from tokens.py, never from hardcoded hexes. Bulletin
rules that shape this layout: radius 0, no shadows or gradients, and
nothing enclosed on four sides, so rows are separated by hairlines
rather than boxed into cards. Product names set in mono, uppercase,
tracked; the house sets in Spectral.

Content comes from data/events.json, which is generated by
build_events.py from whole days only, so every number on this page is
a settled one.
"""
import json
import os

import tokens as T

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EVENTS = os.path.join(REPO, "data", "events.json")
OUT = os.path.join(REPO, "docs", "fires", "index.html")

TAG_TEXT = {
    "enso": "ENSO-loaded window",
    "non_enso": "not ENSO-linked",
    "pending": "attribution pending",
}


def build(events_doc, font_prefix="../fonts/"):
    ev = events_doc["events"]
    window = ev[0]["source"] if ev else ""
    rows = []
    for e in ev:
        rows.append(f"""
      <a class="row" href="{e['href']}">
        <span class="stat">{e['stat']}</span>
        <span class="rowmain">
          <span class="region">{e['region']}</span>
          <span class="claim">{e['title']}</span>
        </span>
        <span class="tag tag-{e['attribution']}">{TAG_TEXT[e['attribution']]}</span>
      </a>""")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Fire | The Long Swell</title>
<style>
{T.font_faces_css(font_prefix)}
:root {{
{T.css_variables()}
}}
@media (prefers-color-scheme: dark) {{
  :root {{
{T.css_variables(dark=True)}
  }}
}}
:root[data-theme="dark"] {{
{T.css_variables(dark=True)}
}}
:root[data-theme="light"] {{
{T.css_variables()}
}}
* {{ box-sizing: border-box; }}
body {{
  margin: 0; background: var(--paper); color: var(--ink);
  font-family: "{T.FONT_PROSE}", Georgia, serif;
  font-size: 17px; line-height: 1.55;
}}
main {{ max-width: 760px; margin: 0 auto; padding: 28px 24px 80px; }}

.masthead {{
  display: flex; align-items: baseline; gap: 14px;
  padding-bottom: 10px; border-bottom: 2px solid var(--ink);
}}
.house {{ font-size: 19px; letter-spacing: -0.01em; }}
.product {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 12px; font-weight: 600; text-transform: uppercase;
  letter-spacing: {T.TRACK_PRODUCT}em; color: var(--fire);
}}
.masthead .when {{
  margin-left: auto;
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 11px; letter-spacing: {T.TRACK_LABEL}em;
  text-transform: uppercase; color: var(--ink-faint);
}}

h1 {{
  font-size: 34px; font-weight: 500; line-height: 1.16;
  letter-spacing: -0.015em; margin: 26px 0 12px; text-wrap: balance;
}}
.standfirst {{
  color: var(--ink-soft); margin: 0 0 6px; max-width: 60ch;
}}
.sectionlabel {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 11px; font-weight: 600; letter-spacing: {T.TRACK_LABEL}em;
  text-transform: uppercase; color: var(--ink-faint);
  margin: 38px 0 0; padding-bottom: 8px;
  border-bottom: 1px solid var(--ink);
}}

.row {{
  display: grid;
  grid-template-columns: 5.2rem 1fr auto;
  gap: 18px; align-items: baseline;
  padding: 15px 0; border-bottom: 1px solid var(--rule);
  text-decoration: none; color: inherit;
}}
.row:hover .claim {{ text-decoration: underline; }}
.row:focus-visible {{ outline: 2px solid var(--fire); outline-offset: 3px; }}
.stat {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 30px; font-weight: 600; color: var(--fire);
  letter-spacing: -0.02em; font-variant-numeric: tabular-nums;
}}
.rowmain {{ display: flex; flex-direction: column; gap: 2px; }}
.region {{ font-size: 19px; font-weight: 500; }}
.claim {{ color: var(--ink-soft); font-size: 15.5px; }}
.tag {{
  font-family: "{T.FONT_DATA}", ui-monospace, monospace;
  font-size: 10.5px; letter-spacing: 0.04em; white-space: nowrap;
  padding: 3px 8px; align-self: center;
}}
.tag-non_enso {{ background: var(--tag-notlink-bg); color: var(--tag-notlink-fg); }}
.tag-enso {{ background: var(--tag-loaded-bg); color: var(--tag-loaded-fg); }}
.tag-pending {{ background: var(--tag-pending-bg); color: var(--tag-pending-fg); }}

.note {{
  margin: 22px 0 0; font-size: 14px; color: var(--ink-soft);
  max-width: 62ch;
}}
.foot {{
  margin-top: 44px; padding-top: 14px;
  border-top: 1px solid var(--ink);
  font-size: 13px; color: var(--ink-faint); max-width: 66ch;
}}
.foot p {{ margin: 0 0 9px; }}
.foot b {{ color: var(--ink-soft); font-weight: 500; }}
@media (max-width: 560px) {{
  .row {{ grid-template-columns: 4.2rem 1fr; }}
  .tag {{ grid-column: 2; justify-self: start; margin-top: 4px; }}
  h1 {{ font-size: 27px; }}
}}
</style>
</head>
<body>
<main>
  <div class="masthead">
    <span class="house">The Long Swell</span>
    <span class="product">Fire</span>
    <span class="when">{window}</span>
  </div>

  <h1>Five countries are burning well above their own seasonal normal</h1>
  <p class="standfirst">Every figure below compares a country only with
  itself, against the same calendar week in each year since 2012. That
  is what separates an unusual week from a merely busy one.</p>

  <p class="sectionlabel">Against their own record</p>
  {''.join(rows)}

  <p class="note">Ranked by how far above normal, not by size. Canada
  recorded more than twenty times Spain's detections this week, but
  Canada burns on that scale most summers and Spain does not.</p>

  <div class="foot">
    <p><b>What a detection is.</b> One satellite pixel, about 375 m
    across, seen radiating enough heat to be flagged as actively
    burning on a single overpass. A large fire front registers as many
    pixels at once, and a fire that keeps burning is counted again on
    every pass it stays hot. Detections are not burned area.</p>
    <p><b>Method.</b> NASA FIRMS, VIIRS on Suomi-NPP only so that every
    year is measured by the same sensor, low-confidence detections
    excluded, detections assigned to countries by national boundary
    polygons applied identically in all years. The window is seven
    whole UTC days, refreshed once daily at 06:00 UTC, so no figure
    here is a partial day.</p>
    <p><b>Attribution.</b> Southern and western European fires are
    driven by heat, drought and wind, and people supply nearly all
    ignitions. Canadian boreal fire has its own drivers. None of this
    week's items is presented as an El Nino signal; each carries its
    own tag.</p>
  </div>
</main>
</body>
</html>
"""


def main():
    doc = json.load(open(EVENTS))
    html = build(doc)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(html)
    print(f"wrote {OUT} ({len(html):,} bytes, {len(doc['events'])} rows)")


if __name__ == "__main__":
    main()
