"""Regenerate design/REVIEW_BUNDLE.md.

The visual-language chat can fetch raw file URLs but not GitHub's
directory or compare pages, so it cannot discover files by browsing.
This concatenates everything reviewable into one file it can fetch in a
single request.

Run from the repo root, commit, then hand over a SHA-PINNED url so no
cache can serve a stale copy:

    .venv/bin/python design/make_review_bundle.py
    git add design && git commit -m "..." && git push
    git rev-parse --short HEAD      # put THIS in the url

## Why there is no git sha in the bundle header

There was, and it was wrong every time, which cost a review round. The
generator read `git rev-parse HEAD` before the commit that contained the
file it was writing, so the header always named the previous commit. A
reviewer read it, saw a sha they had already seen, and concluded nothing
had landed when in fact everything had.

A file cannot name the commit that contains it. So the header carries
content digests of the sources instead. Those are computed from the
bytes being embedded, cannot be off by one, and let a reviewer verify
freshness without trusting a hand-maintained field.
"""

from __future__ import annotations

import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "design" / "REVIEW_BUNDLE.md"

# Builders worth arguing about, in reading order rather than file order.
COMPONENTS = [
    "_masthead_html",
    "_attr_tag",
    "_attr_legend",
    "_ocean_heat_html",
    "_render_rung",
    "_map_html",
]

RENDERED = [
    ("archive.html", "8 KB", "the issue index"),
    ("weekly-issue.html", "24 KB", "the El Nino dense data page"),
    ("methodology.html", "53 KB", "what external reviewers read"),
    ("front-page.html", "75 KB", "the front page and global event map"),
]

RAW = ("https://raw.githubusercontent.com/kristjanlepik-commits/"
       "el-nino-tracker")


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def extract_function(source: str, name: str) -> str:
    start = source.index(f"def {name}(")
    nxt = source.find("\ndef ", start + 1)
    return source[start:nxt if nxt > 0 else len(source)].rstrip()


def main() -> None:
    tokens_src = (ROOT / "tokens.py").read_text()
    brief_src = (ROOT / "run_brief.py").read_text()
    readme = (ROOT / "design" / "review" / "README.md").read_text()

    css = re.search(r'_PUBLIC_CSS_TEMPLATE = """(.*?)""".strip\(\)',
                    brief_src, re.S).group(1)
    comps = [extract_function(brief_src, n) for n in COMPONENTS]

    files = "\n".join(
        f"    {RAW}/<sha>/design/review/{name:<19} {size:>6}  {what}"
        for name, size, what in RENDERED)

    body = f"""# The Long Swell design system, single-file review bundle

Generated by `design/make_review_bundle.py`. Do not hand-edit.

**Freshness, without a git sha.** A file cannot name the commit that
contains it. An earlier version of this header tried, was wrong every
time, and cost a review round. Check these instead; they are computed
from the exact bytes embedded below.

| Source | sha256, first 12 |
|---|---|
| `tokens.py` | `{digest(tokens_src)}` |
| `run_brief.py` | `{digest(brief_src)}` |
| `PUBLIC_CSS` as extracted | `{digest(css)}` |

**Fetch with a sha-pinned URL, never the branch name.** Raw URLs on a
branch are cached for a few minutes and can serve a stale copy; a
sha-pinned path is immutable.

    {RAW}/<sha>/design/REVIEW_BUNDLE.md

This file exists because GitHub's directory and compare pages are
blocked on the reviewing side while raw file URLs are not, so files
cannot be discovered by browsing.

The four rendered pages are too large to inline. Fetch individually:

{files}

---

{readme}

---

# tokens.py, complete

```python
{tokens_src}```

---

# PUBLIC_CSS, complete

Token values are substituted in at build time from `tokens.py`; the
`/*VARS_LIGHT*/` and `/*VARS_DARK*/` markers are where
`css_variables()` output lands.

```css
{css}```

---

# Component builders

```python
{chr(10).join(chr(10) + c for c in comps)}
```
"""
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(body)} chars")
    for label, src in (("tokens.py", tokens_src), ("run_brief.py", brief_src),
                       ("PUBLIC_CSS", css)):
        print(f"  {label:13} {digest(src)}")


if __name__ == "__main__":
    main()
