"""Render docs/pacific-sst.png, the El Nino field under the front-page map.

RUN BY THE MONDAY WORKFLOW, and by hand between runs. This docstring
said "MANUAL ... nothing in the weekly pipeline runs this" until
2026-09-06, and by then it was false: .github/workflows/weekly_brief.yml
line 126 calls it. It is still not wired into run_brief.py, which is the
half that stayed true and the half that made the whole sentence read as
true.

That cost something real. The freshness check says this layer is
"regenerated by the Monday job", the docstring said nothing regenerates
it, and a reader reaching for which one to believe finds the file's own
account of itself is the wrong one. I reached that conclusion myself,
here, and had to check the workflow to escape it.

It pulls live data, writes two committed assets, and stops:

    docs/pacific-sst.png    the field, transparent outside the band
    docs/pacific-sst.json   what the PNG shows, so the page can label it

That split is the point. The map needs a gridded SST field, no fetcher
returns one, and promoting this into the weekly run is the ENSO
tracker's call on their surface rather than something design should
smuggle in. Until they do, the asset is refreshed by running this by
hand and committing the result, and the JSON carries the observation
date so the page can say how old the picture is instead of implying it
is current.

    .venv/bin/python design/make_pacific_sst.py

Why this product. The 1 degree weekly OISST v2 that the obvious spec
reaches for stopped updating on 2023-01-29, so it would have rendered a
map three and a half years stale. This uses the live 0.25 degree v2.1
daily product, subset over OPeNDAP before transfer, so the 271 MB and
1.4 GB whole-file sizes are not what moves.

Extent is the eastern Pacific only, dateline to the South American
coast. The western half of the basin sits on the far side of the
map's antimeridian seam and rendering it too put a second, disconnected
copy of the same event against Australia. One side reads as a crop that
continues past the edge, which is the intent: this is an intrigue
generator on a global map, not the full picture. The full picture
belongs on the El Nino page.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import xarray as xr
import matplotlib.image as mpimg

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import tokens as T  # noqa: E402

BASE = "https://psl.noaa.gov/thredds/dodsC/Datasets/noaa.oisst.v2.highres"
OBS = f"{BASE}/sst.day.mean.2026.nc"
CLIM = f"{BASE}/sst.day.mean.ltm.1991-2020.nc"

LON_W, LON_E = -180.0, -70.0
# The band is wide enough that its own edges land in near-neutral water,
# which is what softens them. An earlier version cropped at 22 degrees
# and faded the outer rows to transparent to stop the block looking
# pasted onto the ocean. That was the wrong fix: ANOMALY[4] is #E8E7E2
# against a #F1F0EC page, so an unremarkable value already vanishes into
# the paper by design, and compositing a step over the page produces a
# colour the legend does not print, so a reader cannot decode the
# margins and cannot tell which margins they are allowed to trust.
# Measured on the 2026-07-26 field: at 22N only 3% of the edge row sits
# in the neutral step, at 28N it is 59%. So widen the crop and let the
# palette do it. Where an edge still lands on live values a hard edge
# plus a stated note is honest; alpha is not.
LAT_S, LAT_N = -28.0, 28.0
DAYS = 7
UPSCALE = 3          # keeps the nine steps crisp once the browser scales it

# VD's ruling 2026-08-12, option 13a. Cells whose anomaly is smaller
# than this draw as paper. The window stays at 28 degrees.
FILL_FLOOR = 1.0

PNG = ROOT / "docs" / "pacific-sst.png"
META = ROOT / "docs" / "pacific-sst.json"


def _connected_water(water, lats, lons, seed_lat, seed_lon):
    """Water cells reachable from a seed without crossing land.

    Plain breadth-first fill over a 100k-cell grid, four-connected, so it
    needs no new dependency. Used to keep the Pacific and discard the
    Gulf, Caribbean and Atlantic that share this longitude window.
    """
    i = int(np.argmin(np.abs(lats - seed_lat)))
    j = int(np.argmin(np.abs(lons - seed_lon)))
    if not water[i, j]:
        raise SystemExit(f"seed at {seed_lat},{seed_lon} is not water; "
                         "pick a seed in open ocean")
    seen = np.zeros_like(water, dtype=bool)
    seen[i, j] = True
    stack = [(i, j)]
    h, w = water.shape
    while stack:
        y, x = stack.pop()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            ny, nx = y + dy, x + dx
            if 0 <= ny < h and 0 <= nx < w and water[ny, nx] and not seen[ny, nx]:
                seen[ny, nx] = True
                stack.append((ny, nx))
    return seen


def _hex_to_rgb(s: str) -> tuple:
    s = s.lstrip("#")
    return tuple(int(s[i:i + 2], 16) for i in (0, 2, 4))


def main() -> None:
    obs = xr.open_dataset(OBS)
    clim = xr.open_dataset(CLIM, decode_times=False)

    last = obs.sst.isel(time=slice(-DAYS, None))
    when = str(last.time.values[-1])[:10]
    doys = [np.datetime64(str(t)[:10]).astype("datetime64[D]").astype(object)
            .timetuple().tm_yday for t in last.time.values]

    lat = obs.lat.values
    lat_slice = (slice(LAT_S, LAT_N) if lat[0] < lat[-1]
                 else slice(LAT_N, LAT_S))
    sel = dict(lat=lat_slice, lon=slice(LON_W % 360, LON_E % 360))

    week = last.sel(**sel).mean("time")
    base = clim.sst.isel(time=[d - 1 for d in doys]).sel(**sel).mean("time")
    anom = (week.values - base.values).astype("float64")
    lats = week.lat.values
    if lats[0] < lats[-1]:                 # north must be row 0 for the PNG
        anom, lats = anom[::-1, :], lats[::-1]

    finite = np.isfinite(anom)
    clipped = float(np.mean(np.abs(anom[finite]) > T.OCEAN_SCALE)) if finite.any() else 0.0
    print(f"week to {when}: {anom.shape}, "
          f"{np.nanmin(anom):+.2f} to {np.nanmax(anom):+.2f} C, "
          f"{clipped * 100:.2f}% beyond +/-{T.OCEAN_SCALE}")

    # Nine discrete steps, the same ones tokens.ANOMALY prints in the
    # legend, so every colour on the map can be decoded off it. The fade
    # is alpha only and never touches the colour, so it cannot move a
    # value into a neighbouring step.
    edges = np.linspace(-T.OCEAN_SCALE, T.OCEAN_SCALE, len(T.ANOMALY) + 1)[1:-1]
    idx = np.digitize(np.nan_to_num(anom, nan=0.0), edges)
    palette = np.array([_hex_to_rgb(c) for c in T.ANOMALY], dtype=np.uint8)

    # Pacific only. The longitude window runs to 70W so it reaches the
    # Peruvian coast, but at its northern end that window also contains
    # the Gulf of Mexico, the Caribbean and a slice of the Atlantic, and
    # those were rendering as part of a block captioned Pacific SST.
    # Rather than hardcode a cutout, keep only the water connected to a
    # seed in the central Pacific. Inside this crop the basins are not
    # connected to each other: the Americas span the full latitude range
    # and Panama closes the isthmus, so a flood fill separates them
    # exactly. No coordinates to maintain, and it stays correct if the
    # window changes.
    pacific = _connected_water(finite, lats, week.lon.values, 0.0, 200.0)
    dropped = int(finite.sum() - pacific.sum())
    print(f"non-Pacific water dropped: {dropped:,} cells "
          f"({100.0 * dropped / max(1, finite.sum()):.1f}% of water in window)")

    rgba = np.zeros(anom.shape + (4,), dtype=np.uint8)
    rgba[..., :3] = palette[idx]
    # Alpha stays binary, so every drawn pixel is exactly a colour the
    # legend prints and nothing is composited (D-024).
    #
    # The neutral step is not drawn at all. ANOMALY[4] is #E8E7E2 against
    # a #F1F0EC page, which the palette intends to vanish into the paper,
    # and across a field it very nearly does. But the difference is
    # 1.086:1, and that is enough to make a dead-straight crop edge
    # hundreds of pixels long visible as a rectangle, which is what a
    # wider crop was supposed to cure and did not. Leaving the step
    # undrawn gets the intended result exactly rather than approximately:
    # an unremarkable value shows the page, which is what #E8E7E2 on
    # #F1F0EC was always trying to look like. This is not the alpha fade
    # D-024 rejects. That composited a step into an undecodable colour;
    # this draws each step at full opacity or not at all, and the note
    # tells the reader that page inside the band means near zero.
    neutral_step = len(T.ANOMALY) // 2
    # VD's ruling, option 13a: THRESHOLD THE FILL AT +/- 1.0 DEGREES.
    #
    # Their diagnosis, which is better than the one in the ask I sent them.
    # I asked for a quieter ramp; the root cause is not the ramp's weight
    # but that almost nothing was unshaded. The palest warm step covered
    # most of the basin, because most of the basin is slightly above its
    # 1991-2020 normal, which is true and is not news. The field spent its
    # whole ink budget saying "warmer than average nearly everywhere" and
    # had nothing left to say where the event is.
    #
    # So this is the palette's founding rule being applied where it was
    # not: colour is earned by DEPARTURE from a baseline, and a +0.3 cell
    # has not earned any. It is not a cosmetic reduction, and it removes
    # nothing the field was actually reporting.
    #
    # NOT an opacity change. VD were explicit: the field carries data and
    # attenuation is for furniture. Each step still draws at full opacity
    # or not at all.
    drawn = pacific & (idx != neutral_step) & (np.abs(anom) >= FILL_FLOOR)
    rgba[..., 3] = np.where(drawn, 255, 0).astype(np.uint8)

    # The share now left as paper, so the caption can state it rather than
    # a template asserting it. Companion to fraction_beyond_scale: one says
    # what runs off the top of the scale, this says what sits below its
    # bottom, and both are derived every run.
    _water = pacific & np.isfinite(anom)
    unshaded = (float(np.mean(np.abs(anom[_water]) < FILL_FLOOR))
                if _water.any() else 0.0)
    print(f"unshaded below +/-{FILL_FLOOR} C: {unshaded:.1%} of water in window")

    # How neutral the band's own edges are, since that is what has to do
    # the softening now. Reported so a future refresh cannot quietly
    # start cutting through a live value without anyone noticing.
    neutral = float(edges[len(edges) // 2] - edges[len(edges) // 2 - 1]) / 2.0
    def edge_neutral(row):
        r = row[np.isfinite(row)]
        return round(float(np.mean(np.abs(r) < neutral)), 3) if r.size else None
    north, south = edge_neutral(anom[0]), edge_neutral(anom[-1])
    print(f"edge in neutral step: north {north}, south {south} "
          f"(neutral is |anomaly| < {neutral:.3f} C)")

    if UPSCALE > 1:
        rgba = np.repeat(np.repeat(rgba, UPSCALE, axis=0), UPSCALE, axis=1)

    PNG.parent.mkdir(parents=True, exist_ok=True)
    mpimg.imsave(PNG, rgba)

    # The extent is written next to the image so the page positions it
    # from the data rather than from numbers retyped into a template. A
    # map that draws the field half a basin off is worse than no field.
    META.write_text(json.dumps({
        "observation_date": when,
        "days_averaged": DAYS,
        "lon_west": LON_W, "lon_east": LON_E,
        "lat_south": float(min(lats)), "lat_north": float(max(lats)),
        "anomaly_min": round(float(np.nanmin(anom)), 2),
        "anomaly_max": round(float(np.nanmax(anom)), 2),
        "full_scale": T.OCEAN_SCALE,
        "fraction_beyond_scale": round(clipped, 4),
        "fill_floor": FILL_FLOOR,
        "fraction_unshaded": round(unshaded, 4),
        "edge_neutral_north": north,
        "edge_neutral_south": south,
        "source": "NOAA OISST v2.1 (0.25 deg daily) vs 1991-2020 climatology",
        "source_url": OBS,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generator": "design/make_pacific_sst.py, run by hand",
    }, indent=2) + "\n")
    print(f"wrote {PNG.relative_to(ROOT)} ({PNG.stat().st_size:,} bytes)")
    print(f"wrote {META.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
